package com.elxvro.scan.ui.screens

import android.graphics.Bitmap
import android.widget.Toast
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Download
import androidx.compose.material.icons.outlined.QrCode2
import androidx.compose.material.icons.outlined.Share
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import com.elxvro.scan.ScanStore
import com.elxvro.scan.barcode.BarcodeCreatePolicy
import com.elxvro.scan.barcode.BarcodeCreateResult
import com.elxvro.scan.barcode.BarcodeCreateType
import com.elxvro.scan.barcode.BarcodeEncodingPolicy
import com.elxvro.scan.barcode.BarcodeImageActions
import com.elxvro.scan.barcode.BarcodeImageUtil
import com.elxvro.scan.ui.components.ReferenceChip
import com.elxvro.scan.ui.components.ReferenceHeader
import com.elxvro.scan.ui.components.ReferencePrimaryButton
import com.elxvro.scan.ui.theme.ScanTokens

@Composable
fun BarcodeCreateScreen(
    store: ScanStore,
    onBack: () -> Unit
) {
    val context = androidx.compose.ui.platform.LocalContext.current
    var type by remember { mutableStateOf(BarcodeCreateType.CODE_128) }
    var value by remember { mutableStateOf("") }
    var normalizedValue by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<Bitmap?>(null) }

    fun toast(message: String) = Toast.makeText(context, message, Toast.LENGTH_SHORT).show()

    fun resetOutput() {
        generated = null
        normalizedValue = ""
    }

    fun generate() {
        when (val result = BarcodeCreatePolicy.validate(type, value)) {
            is BarcodeCreateResult.Invalid -> toast(result.message)
            is BarcodeCreateResult.Valid -> {
                runCatching {
                    BarcodeImageUtil.create(type, result.normalizedValue)
                }.onSuccess { bitmap ->
                    generated = bitmap
                    normalizedValue = result.normalizedValue
                    store.add(
                        value = result.normalizedValue,
                        format = type.historyFormat,
                        kind = "BARCODE"
                    )
                    toast("Barkod oluşturuldu ve geçmişe eklendi")
                }.onFailure {
                    toast("Barkod oluşturulamadı")
                }
            }
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(ScanTokens.Ink)
    ) {
        ReferenceHeader(title = "Barkod Oluştur", onBack = onBack)

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .horizontalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 10.dp),
            horizontalArrangement = Arrangement.spacedBy(7.dp)
        ) {
            BarcodeCreateType.entries.forEach { item ->
                ReferenceChip(
                    text = item.label,
                    selected = type == item,
                    onClick = {
                        if (type != item) {
                            type = item
                            value = ""
                            resetOutput()
                        }
                    }
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(
                    ScanTokens.Paper,
                    RoundedCornerShape(topStart = 20.dp, topEnd = 20.dp)
                )
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Text(
                text = barcodeDescription(type),
                color = ScanTokens.Muted,
                style = MaterialTheme.typography.bodySmall,
                modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp)
            )

            OutlinedTextField(
                value = value,
                onValueChange = {
                    value = it
                    resetOutput()
                },
                modifier = Modifier.fillMaxWidth(),
                label = { Text(barcodeInputLabel(type)) },
                singleLine = true,
                keyboardOptions = KeyboardOptions(
                    keyboardType = if (type == BarcodeCreateType.CODE_128) {
                        KeyboardType.Ascii
                    } else {
                        KeyboardType.Number
                    }
                ),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = ScanTokens.Blue,
                    unfocusedBorderColor = ScanTokens.Divider,
                    focusedContainerColor = Color.White,
                    unfocusedContainerColor = Color.White
                )
            )

            generated?.let { bitmap ->
                val spec = BarcodeEncodingPolicy.canvas(type)
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 16.dp)
                        .background(Color.White, RoundedCornerShape(14.dp))
                        .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp))
                        .padding(14.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Image(
                        bitmap = bitmap.asImageBitmap(),
                        contentDescription = "Oluşturulan barkod",
                        modifier = Modifier
                            .fillMaxWidth()
                            .aspectRatio(spec.width.toFloat() / spec.height.toFloat())
                    )
                }

                Text(
                    text = normalizedValue,
                    color = ScanTokens.Text,
                    fontWeight = FontWeight.SemiBold,
                    style = MaterialTheme.typography.bodyMedium,
                    modifier = Modifier.fillMaxWidth().padding(top = 10.dp)
                )
                Text(
                    text = type.label + " • Geçmişe kaydedildi",
                    color = ScanTokens.Muted,
                    style = MaterialTheme.typography.bodySmall,
                    modifier = Modifier.fillMaxWidth().padding(top = 2.dp)
                )
            } ?: Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 16.dp)
                    .height(220.dp)
                    .background(Color.White, RoundedCornerShape(14.dp))
                    .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp)),
                contentAlignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(
                        Icons.Outlined.QrCode2,
                        contentDescription = null,
                        tint = ScanTokens.Blue
                    )
                    Text(
                        text = "Barkod önizlemesi",
                        color = ScanTokens.Muted,
                        style = MaterialTheme.typography.bodyMedium,
                        modifier = Modifier.padding(top = 6.dp)
                    )
                }
            }

            ReferencePrimaryButton(
                text = "Barkod Oluştur",
                onClick = ::generate,
                modifier = Modifier.fillMaxWidth().padding(top = 14.dp)
            )

            Row(
                modifier = Modifier.fillMaxWidth().padding(top = 10.dp),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                BarcodeAction(
                    icon = Icons.Outlined.Download,
                    label = "Kaydet",
                    enabled = generated != null,
                    modifier = Modifier.weight(1f)
                ) {
                    generated?.let { bitmap ->
                        runCatching { BarcodeImageActions.save(context, bitmap) }
                            .onSuccess(::toast)
                            .onFailure { toast("Barkod kaydedilemedi") }
                    }
                }
                BarcodeAction(
                    icon = Icons.Outlined.Share,
                    label = "Paylaş",
                    enabled = generated != null,
                    modifier = Modifier.weight(1f)
                ) {
                    generated?.let { bitmap ->
                        runCatching { BarcodeImageActions.share(context, bitmap) }
                            .onFailure { toast("Barkod paylaşılamadı") }
                    }
                }
            }

            Spacer(Modifier.height(20.dp))
        }
    }
}

@Composable
private fun BarcodeAction(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    label: String,
    enabled: Boolean,
    modifier: Modifier = Modifier,
    onClick: () -> Unit
) {
    Row(
        modifier = modifier
            .background(Color.White, RoundedCornerShape(12.dp))
            .border(1.dp, ScanTokens.Divider, RoundedCornerShape(12.dp))
            .clickable(enabled = enabled, onClick = onClick)
            .padding(horizontal = 12.dp, vertical = 13.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.Center
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = if (enabled) ScanTokens.Blue else ScanTokens.Muted
        )
        Text(
            text = label,
            color = if (enabled) ScanTokens.Text else ScanTokens.Muted,
            style = MaterialTheme.typography.bodyMedium,
            modifier = Modifier.padding(start = 7.dp)
        )
    }
}

private fun barcodeInputLabel(type: BarcodeCreateType): String = when (type) {
    BarcodeCreateType.CODE_128 -> "Metin veya numara"
    BarcodeCreateType.EAN_13 -> "12 veya 13 hane"
    BarcodeCreateType.UPC_A -> "11 veya 12 hane"
}

private fun barcodeDescription(type: BarcodeCreateType): String = when (type) {
    BarcodeCreateType.CODE_128 -> "Ürün, stok, sipariş ve özel kodlar için metin veya sayı kullan."
    BarcodeCreateType.EAN_13 -> "12 hane girersen kontrol hanesi otomatik hesaplanır; 13 hane girersen doğrulanır."
    BarcodeCreateType.UPC_A -> "11 hane girersen kontrol hanesi otomatik hesaplanır; 12 hane girersen doğrulanır."
}
