package com.elxvro.scan.ui.screens

import android.graphics.Color as AndroidColor
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Download
import androidx.compose.material.icons.outlined.ExpandLess
import androidx.compose.material.icons.outlined.ExpandMore
import androidx.compose.material.icons.outlined.Share
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.elxvro.scan.QrCodeUtil
import com.elxvro.scan.QrImageActions
import com.elxvro.scan.QrPayloadBuilder
import com.elxvro.scan.WifiSecurity
import com.elxvro.scan.ui.components.ReferenceChip
import com.elxvro.scan.ui.components.ReferenceHeader
import com.elxvro.scan.ui.components.ReferencePrimaryButton
import com.elxvro.scan.ui.theme.ScanTokens

private val createTypes = listOf("URL", "Metin", "Wi-Fi", "Kişi", "Telefon", "E-posta", "SMS", "Konum", "Takvim")

@Composable
fun CreateScreen(onBack: () -> Unit) {
    val context = androidx.compose.ui.platform.LocalContext.current
    var type by remember { mutableStateOf("URL") }
    var primary by remember { mutableStateOf("") }
    var secondary by remember { mutableStateOf("") }
    var wifiSecurity by remember { mutableStateOf(WifiSecurity.WPA) }
    var generated by remember { mutableStateOf<android.graphics.Bitmap?>(null) }
    var payload by remember { mutableStateOf("") }
    var settingsExpanded by remember { mutableStateOf(false) }
    var qrSize by remember { mutableIntStateOf(900) }
    var qrMargin by remember { mutableIntStateOf(2) }
    var foreground by remember { mutableIntStateOf(AndroidColor.BLACK) }

    fun toast(message: String) = Toast.makeText(context, message, Toast.LENGTH_SHORT).show()

    fun resetGenerated() {
        generated = null
        payload = ""
    }

    fun buildQr() {
        if (primary.trim().isBlank()) {
            toast("Ana alan boş bırakılamaz")
            return
        }
        payload = when (type) {
            "Wi-Fi" -> QrPayloadBuilder.buildWifi(primary, secondary, wifiSecurity)
            else -> QrPayloadBuilder.build(type, primary, secondary)
        }
        generated = QrCodeUtil.create(
            text = payload,
            size = qrSize,
            margin = qrMargin,
            foreground = foreground
        )
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(ScanTokens.Ink)
    ) {
        ReferenceHeader(title = "QR Kod Oluştur", onBack = onBack)

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .horizontalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 10.dp),
            horizontalArrangement = Arrangement.spacedBy(7.dp)
        ) {
            createTypes.forEach { item ->
                ReferenceChip(
                    text = item,
                    selected = type == item,
                    onClick = {
                        if (type != item) {
                            type = item
                            primary = ""
                            secondary = ""
                            resetGenerated()
                        }
                    }
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(
                    ScanTokens.Paper,
                    RoundedCornerShape(topStart = 20.dp, topEnd = 20.dp)
                )
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Field(
                value = primary,
                onValueChange = { primary = it; resetGenerated() },
                label = primaryLabel(type)
            )

            if (needsSecondary(type) && !(type == "Wi-Fi" && wifiSecurity == WifiSecurity.OPEN)) {
                Spacer(Modifier.height(10.dp))
                Field(
                    value = secondary,
                    onValueChange = { secondary = it; resetGenerated() },
                    label = secondaryLabel(type),
                    password = type == "Wi-Fi"
                )
            }

            if (type == "Wi-Fi") {
                Text(
                    "Güvenlik",
                    color = ScanTokens.Muted,
                    style = MaterialTheme.typography.bodySmall,
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 12.dp, bottom = 6.dp)
                )
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(7.dp)
                ) {
                    listOf(
                        "WPA/WPA2" to WifiSecurity.WPA,
                        "WEP" to WifiSecurity.WEP,
                        "Şifresiz" to WifiSecurity.OPEN
                    ).forEach { (label, mode) ->
                        ReferenceChip(label, wifiSecurity == mode) {
                            wifiSecurity = mode
                            if (mode == WifiSecurity.OPEN) secondary = ""
                            resetGenerated()
                        }
                    }
                }
            }

            generated?.let { bitmap ->
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 16.dp)
                        .background(Color.White, RoundedCornerShape(14.dp))
                        .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp))
                        .padding(18.dp),
                    contentAlignment = Alignment.Center
                ) {
                    androidx.compose.foundation.Image(
                        bitmap = bitmap.asImageBitmap(),
                        contentDescription = "Oluşturulan QR kod",
                        modifier = Modifier
                            .fillMaxWidth(0.82f)
                            .aspectRatio(1f)
                    )
                }
            } ?: Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 16.dp)
                    .height(248.dp)
                    .background(Color.White, RoundedCornerShape(14.dp))
                    .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp)),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    "QR önizlemesi",
                    color = ScanTokens.Muted,
                    style = MaterialTheme.typography.bodyMedium
                )
            }

            Text(
                "QR rengi",
                color = ScanTokens.Muted,
                style = MaterialTheme.typography.bodySmall,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 12.dp, bottom = 8.dp)
            )
            ColorSwatches(
                selected = foreground,
                onSelect = {
                    foreground = it
                    if (payload.isNotBlank()) generated = QrCodeUtil.create(payload, qrSize, qrMargin, foreground)
                }
            )

            ReferencePrimaryButton(
                text = "QR Kod Oluştur",
                onClick = ::buildQr,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 14.dp)
            )

            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 10.dp),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                SecondaryAction(
                    icon = Icons.Outlined.Download,
                    text = "Kaydet",
                    modifier = Modifier.weight(1f),
                    enabled = generated != null
                ) {
                    generated?.let { bitmap ->
                        runCatching { QrImageActions.save(context, bitmap) }
                            .onSuccess(::toast)
                            .onFailure { toast("QR kaydedilemedi") }
                    }
                }
                SecondaryAction(
                    icon = Icons.Outlined.Share,
                    text = "Paylaş",
                    modifier = Modifier.weight(1f),
                    enabled = generated != null
                ) {
                    generated?.let { bitmap ->
                        runCatching { QrImageActions.share(context, bitmap) }
                            .onFailure { toast("QR paylaşılamadı") }
                    }
                }
            }

            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 10.dp)
                    .background(Color.White, RoundedCornerShape(12.dp))
                    .border(1.dp, ScanTokens.Divider, RoundedCornerShape(12.dp))
                    .clickable { settingsExpanded = !settingsExpanded }
                    .padding(horizontal = 14.dp, vertical = 12.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column(Modifier.weight(1f)) {
                    Text("QR Ayarları", color = ScanTokens.Text, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Medium)
                    Text("${qrSize}px • Kenar $qrMargin", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall)
                }
                Icon(
                    if (settingsExpanded) Icons.Outlined.ExpandLess else Icons.Outlined.ExpandMore,
                    contentDescription = null,
                    tint = ScanTokens.Muted
                )
            }

            if (settingsExpanded) {
                Text("Boyut", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                Row(Modifier.fillMaxWidth().padding(top = 6.dp), horizontalArrangement = Arrangement.spacedBy(7.dp)) {
                    listOf(512, 900, 1200).forEach { size ->
                        CompactLightChip("$size", qrSize == size, Modifier.weight(1f)) {
                            qrSize = size
                            if (payload.isNotBlank()) generated = QrCodeUtil.create(payload, qrSize, qrMargin, foreground)
                        }
                    }
                }
                Text("Kenar boşluğu", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                Row(Modifier.fillMaxWidth().padding(top = 6.dp), horizontalArrangement = Arrangement.spacedBy(7.dp)) {
                    listOf(1, 2, 4).forEach { margin ->
                        CompactLightChip("$margin", qrMargin == margin, Modifier.weight(1f)) {
                            qrMargin = margin
                            if (payload.isNotBlank()) generated = QrCodeUtil.create(payload, qrSize, qrMargin, foreground)
                        }
                    }
                }
            }
            Spacer(Modifier.height(18.dp))
        }
    }
}

@Composable
private fun Field(
    value: String,
    onValueChange: (String) -> Unit,
    label: String,
    password: Boolean = false
) {
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        label = { Text(label) },
        singleLine = true,
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        visualTransformation = if (password) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,
        colors = OutlinedTextFieldDefaults.colors(
            focusedContainerColor = Color.White,
            unfocusedContainerColor = Color.White,
            focusedBorderColor = ScanTokens.Blue,
            unfocusedBorderColor = ScanTokens.Divider,
            focusedTextColor = ScanTokens.Text,
            unfocusedTextColor = ScanTokens.Text,
            focusedLabelColor = ScanTokens.Blue,
            unfocusedLabelColor = ScanTokens.Muted,
            cursorColor = ScanTokens.Blue
        )
    )
}

@Composable
private fun ColorSwatches(selected: Int, onSelect: (Int) -> Unit) {
    val colors = listOf(
        Color(0xFF0068F8),
        Color(0xFF1593FF),
        Color(0xFFCF24E8),
        Color(0xFF7539E8),
        Color(0xFF0D9F55),
        Color(0xFF101820)
    )
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        colors.forEach { color ->
            val value = color.toArgb()
            Box(
                modifier = Modifier
                    .size(30.dp)
                    .border(
                        width = if (selected == value) 2.dp else 1.dp,
                        color = if (selected == value) ScanTokens.Blue else ScanTokens.Divider,
                        shape = CircleShape
                    )
                    .padding(4.dp)
                    .background(color, CircleShape)
                    .clickable { onSelect(value) }
            )
        }
    }
}

@Composable
private fun SecondaryAction(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    text: String,
    modifier: Modifier = Modifier,
    enabled: Boolean,
    onClick: () -> Unit
) {
    Column(
        modifier = modifier
            .height(64.dp)
            .background(Color.White, RoundedCornerShape(12.dp))
            .border(1.dp, ScanTokens.Divider, RoundedCornerShape(12.dp))
            .clickable(enabled = enabled, onClick = onClick),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(icon, contentDescription = null, tint = if (enabled) ScanTokens.Text else ScanTokens.Muted.copy(alpha = 0.5f), modifier = Modifier.size(20.dp))
        Text(text, color = if (enabled) ScanTokens.Text else ScanTokens.Muted.copy(alpha = 0.5f), style = MaterialTheme.typography.bodySmall, modifier = Modifier.padding(top = 3.dp))
    }
}

@Composable
private fun CompactLightChip(text: String, selected: Boolean, modifier: Modifier, onClick: () -> Unit) {
    Box(
        modifier = modifier
            .height(38.dp)
            .background(if (selected) ScanTokens.Blue.copy(alpha = 0.10f) else Color.White, RoundedCornerShape(10.dp))
            .border(1.dp, if (selected) ScanTokens.Blue else ScanTokens.Divider, RoundedCornerShape(10.dp))
            .clickable(onClick = onClick),
        contentAlignment = Alignment.Center
    ) {
        Text(text, color = if (selected) ScanTokens.Blue else ScanTokens.Text, style = MaterialTheme.typography.bodySmall, fontWeight = FontWeight.Medium)
    }
}

private fun primaryLabel(type: String): String = when (type) {
    "URL" -> "Web Sitesi URL"
    "Metin" -> "Metin"
    "Wi-Fi" -> "Wi-Fi adı (SSID)"
    "Kişi" -> "Ad Soyad"
    "Telefon" -> "Telefon numarası"
    "E-posta" -> "E-posta adresi"
    "SMS" -> "Telefon numarası"
    "Konum" -> "Enlem,Boylam"
    "Takvim" -> "Etkinlik başlığı"
    else -> "İçerik"
}

private fun secondaryLabel(type: String): String = when (type) {
    "Wi-Fi" -> "Wi-Fi şifresi"
    "Kişi" -> "Telefon"
    "SMS" -> "Mesaj"
    "Takvim" -> "Başlangıç (örn. 20261002T120000Z)"
    else -> "Ek bilgi"
}

private fun needsSecondary(type: String): Boolean = type in setOf("Wi-Fi", "Kişi", "SMS", "Takvim")
