package com.elxvro.scan.ui.screens

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color as AndroidColor
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Download
import androidx.compose.material.icons.outlined.ExpandLess
import androidx.compose.material.icons.outlined.ExpandMore
import androidx.compose.material.icons.outlined.Image
import androidx.compose.material.icons.outlined.QrCode2
import androidx.compose.material.icons.outlined.Share
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.elxvro.scan.QrCodeUtil
import com.elxvro.scan.QrImageActions
import com.elxvro.scan.QrPayloadBuilder
import com.elxvro.scan.WifiSecurity
import com.elxvro.scan.billing.ProEntitlement
import com.elxvro.scan.pro.QrGenerationPolicy
import com.elxvro.scan.pro.QrPremiumPolicy
import com.elxvro.scan.qrcard.ElxvroBrandLogo
import com.elxvro.scan.qrcard.LogoMode
import com.elxvro.scan.qrcard.QrLogoComposer
import com.elxvro.scan.ui.components.ProBadge
import com.elxvro.scan.ui.components.ReferenceChip
import com.elxvro.scan.ui.components.ReferenceHeader
import com.elxvro.scan.ui.components.ReferencePrimaryButton
import com.elxvro.scan.ui.theme.ScanTokens

private val createTypes = listOf("URL", "Metin", "Wi-Fi", "Kişi", "Telefon", "E-posta", "SMS", "Konum", "Takvim")

@Composable
fun CreateScreen(
    entitlement: ProEntitlement,
    onOpenPaywall: () -> Unit,
    onOpenQrCard: (String) -> Unit,
    onBack: () -> Unit
) {
    val context = androidx.compose.ui.platform.LocalContext.current
    val isPro = entitlement is ProEntitlement.Pro
    var type by remember { mutableStateOf("URL") }
    var primary by remember { mutableStateOf("") }
    var secondary by remember { mutableStateOf("") }
    var wifiSecurity by remember { mutableStateOf(WifiSecurity.WPA) }
    var generated by remember { mutableStateOf<Bitmap?>(null) }
    var payload by remember { mutableStateOf("") }
    var settingsExpanded by remember { mutableStateOf(false) }
    var qrSize by remember { mutableIntStateOf(900) }
    var qrMargin by remember { mutableIntStateOf(4) }
    var foreground by remember { mutableIntStateOf(AndroidColor.BLACK) }
    var background by remember { mutableIntStateOf(AndroidColor.WHITE) }
    var logoMode by remember { mutableStateOf(QrPremiumPolicy.defaultLogoMode(entitlement)) }
    var logoScale by remember { mutableFloatStateOf(0.18f) }
    var customLogo by remember { mutableStateOf<Bitmap?>(null) }

    fun toast(message: String) = Toast.makeText(context, message, Toast.LENGTH_SHORT).show()

    val logoPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        if (uri != null) {
            runCatching {
                context.contentResolver.openInputStream(uri)?.use(BitmapFactory::decodeStream)
                    ?: error("Logo okunamadı")
            }.onSuccess {
                customLogo = it
                logoMode = LogoMode.CUSTOM
                generated = null
            }.onFailure { toast("Logo açılamadı") }
        }
    }

    fun resetGenerated() {
        generated = null
        payload = ""
    }

    fun selectedLogoBitmap(): Bitmap? = when (logoMode) {
        LogoMode.ELXVRO -> ElxvroBrandLogo.bitmap(context)
        LogoMode.CUSTOM -> customLogo
        LogoMode.NONE -> null
    }

    fun renderQr(text: String): Bitmap {
        val options = QrGenerationPolicy.resolve(
            requestedSize = qrSize,
            requestedMargin = qrMargin,
            logoMode = logoMode,
            entitlement = entitlement
        )
        val raw = QrCodeUtil.create(
            text = text,
            size = options.size,
            margin = options.margin,
            foreground = foreground,
            background = background,
            highErrorCorrection = options.highErrorCorrection
        )
        val logo = selectedLogoBitmap()
        return if (logo != null) QrLogoComposer.compose(raw, logo, logoScale) else raw
    }

    fun buildQr() {
        if (primary.trim().isBlank()) {
            toast("Ana alan boş bırakılamaz")
            return
        }
        if (logoMode == LogoMode.CUSTOM && customLogo == null) {
            logoPicker.launch("image/*")
            return
        }
        payload = when (type) {
            "Wi-Fi" -> QrPayloadBuilder.buildWifi(primary, secondary, wifiSecurity)
            else -> QrPayloadBuilder.build(type, primary, secondary)
        }
        runCatching { renderQr(payload) }
            .onSuccess { generated = it }
            .onFailure { toast("QR oluşturulamadı") }
    }

    fun rebuildGenerated() {
        if (payload.isNotBlank()) {
            runCatching { renderQr(payload) }
                .onSuccess { generated = it }
                .onFailure { generated = null }
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(ScanTokens.Ink)
    ) {
        ReferenceHeader(title = "QR Kod Oluştur", onBack = onBack)

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .horizontalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 10.dp),
            horizontalArrangement = Arrangement.spacedBy(7.dp)
        ) {
            createTypes.forEach { item ->
                ReferenceChip(
                    text = item,
                    selected = type == item,
                    onClick = {
                        if (type != item) {
                            type = item
                            primary = ""
                            secondary = ""
                            resetGenerated()
                        }
                    }
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(ScanTokens.Paper, RoundedCornerShape(topStart = 20.dp, topEnd = 20.dp))
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Field(
                value = primary,
                onValueChange = { primary = it; resetGenerated() },
                label = primaryLabel(type)
            )

            if (needsSecondary(type) && !(type == "Wi-Fi" && wifiSecurity == WifiSecurity.OPEN)) {
                Spacer(Modifier.height(10.dp))
                Field(
                    value = secondary,
                    onValueChange = { secondary = it; resetGenerated() },
                    label = secondaryLabel(type),
                    password = type == "Wi-Fi"
                )
            }

            if (type == "Wi-Fi") {
                Text(
                    "Güvenlik",
                    color = ScanTokens.Muted,
                    style = MaterialTheme.typography.bodySmall,
                    modifier = Modifier.fillMaxWidth().padding(top = 12.dp, bottom = 6.dp)
                )
                Row(
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(7.dp)
                ) {
                    listOf(
                        "WPA/WPA2" to WifiSecurity.WPA,
                        "WEP" to WifiSecurity.WEP,
                        "Şifresiz" to WifiSecurity.OPEN
                    ).forEach { (label, mode) ->
                        ReferenceChip(label, wifiSecurity == mode) {
                            wifiSecurity = mode
                            if (mode == WifiSecurity.OPEN) secondary = ""
                            resetGenerated()
                        }
                    }
                }
            }

            generated?.let { bitmap ->
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 16.dp)
                        .background(Color.White, RoundedCornerShape(14.dp))
                        .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp))
                        .padding(18.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Image(
                        bitmap = bitmap.asImageBitmap(),
                        contentDescription = "Oluşturulan QR kod",
                        modifier = Modifier.fillMaxWidth(0.82f).aspectRatio(1f)
                    )
                }
            } ?: Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 16.dp)
                    .height(248.dp)
                    .background(Color.White, RoundedCornerShape(14.dp))
                    .border(1.dp, ScanTokens.Divider, RoundedCornerShape(14.dp)),
                contentAlignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(Icons.Outlined.QrCode2, contentDescription = null, tint = ScanTokens.Blue, modifier = Modifier.size(34.dp))
                    Text("QR önizlemesi", color = ScanTokens.Muted, style = MaterialTheme.typography.bodyMedium, modifier = Modifier.padding(top = 6.dp))
                }
            }

            Text(
                "QR rengi",
                color = ScanTokens.Muted,
                style = MaterialTheme.typography.bodySmall,
                modifier = Modifier.fillMaxWidth().padding(top = 12.dp, bottom = 8.dp)
            )
            ColorSwatches(
                selected = foreground,
                onSelect = {
                    foreground = it
                    rebuildGenerated()
                }
            )

            ReferencePrimaryButton(
                text = "QR Kod Oluştur",
                onClick = ::buildQr,
                modifier = Modifier.fillMaxWidth().padding(top = 14.dp)
            )

            Row(
                modifier = Modifier.fillMaxWidth().padding(top = 10.dp),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                SecondaryAction(Icons.Outlined.Download, "Kaydet", Modifier.weight(1f), generated != null) {
                    generated?.let { bitmap ->
                        runCatching { QrImageActions.save(context, bitmap) }
                            .onSuccess(::toast)
                            .onFailure { toast("QR kaydedilemedi") }
                    }
                }
                SecondaryAction(Icons.Outlined.Share, "Paylaş", Modifier.weight(1f), generated != null) {
                    generated?.let { bitmap ->
                        runCatching { QrImageActions.share(context, bitmap) }
                            .onFailure { toast("QR paylaşılamadı") }
                    }
                }
            }

            QrCardEntry(
                isPro = isPro,
                onClick = { onOpenQrCard(payload.ifBlank { primary.ifBlank { "https://elxvro.com" } }) }
            )

            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 10.dp)
                    .background(Color.White, RoundedCornerShape(12.dp))
                    .border(1.dp, ScanTokens.Divider, RoundedCornerShape(12.dp))
                    .clickable { settingsExpanded = !settingsExpanded }
                    .padding(horizontal = 14.dp, vertical = 12.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column(Modifier.weight(1f)) {
                    Text("QR Ayarları", color = ScanTokens.Text, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Medium)
                    Text("${qrSize}px • Kenar $qrMargin • ${logoLabel(logoMode)}", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall)
                }
                Icon(
                    if (settingsExpanded) Icons.Outlined.ExpandLess else Icons.Outlined.ExpandMore,
                    contentDescription = null,
                    tint = ScanTokens.Muted
                )
            }

            if (settingsExpanded) {
                Text("Boyut", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                Row(
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).padding(top = 6.dp),
                    horizontalArrangement = Arrangement.spacedBy(7.dp)
                ) {
                    listOf(512, 900, 1200, 2048).forEach { size ->
                        val locked = !isPro && size > 900
                        CompactLightChip("$size${if (locked) " PRO" else ""}", qrSize == size) {
                            if (locked) onOpenPaywall() else {
                                qrSize = size
                                rebuildGenerated()
                            }
                        }
                    }
                }

                Text("Logo", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                LogoChoiceRow(logoMode, isPro, onOpenPaywall) { next ->
                    if (next == LogoMode.CUSTOM && customLogo == null) {
                        logoPicker.launch("image/*")
                    } else {
                        logoMode = next
                        rebuildGenerated()
                    }
                }

                if (isPro && logoMode != LogoMode.NONE) {
                    Text("Logo boyutu • ${(logoScale * 100).toInt()}%", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                    Slider(
                        value = logoScale,
                        onValueChange = {
                            logoScale = it
                            generated = null
                        },
                        valueRange = 0.12f..0.20f
                    )
                }

                Text("Kenar boşluğu", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                Row(Modifier.fillMaxWidth().padding(top = 6.dp), horizontalArrangement = Arrangement.spacedBy(7.dp)) {
                    val margins = if (logoMode == LogoMode.NONE) listOf(1, 4, 8) else listOf(4, 8)
                    margins.forEach { margin ->
                        CompactLightChip("$margin", qrMargin == margin, Modifier.weight(1f)) {
                            qrMargin = margin
                            rebuildGenerated()
                        }
                    }
                }

                Text("Arka plan rengi", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(top = 10.dp))
                if (isPro) {
                    BackgroundSwatches(background) {
                        background = it
                        rebuildGenerated()
                    }
                } else {
                    LockedProRow("Özel arka plan renkleri", onOpenPaywall)
                }
            }
            Spacer(Modifier.height(18.dp))
        }
    }
}

@Composable
private fun QrCardEntry(isPro: Boolean, onClick: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(top = 12.dp)
            .background(ScanTokens.Ink, RoundedCornerShape(ScanTokens.RadiusCard))
            .clickable(onClick = onClick)
            .padding(14.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Box(
            modifier = Modifier.size(42.dp).background(ScanTokens.Blue.copy(alpha = 0.16f), RoundedCornerShape(11.dp)),
            contentAlignment = Alignment.Center
        ) {
            Icon(Icons.Outlined.QrCode2, contentDescription = null, tint = ScanTokens.Blue)
        }
        Column(Modifier.weight(1f).padding(horizontal = 11.dp)) {
            Text("QR Kart", color = ScanTokens.TextOnDark, fontWeight = FontWeight.SemiBold)
            Text("Markalı kartvizit, Wi-Fi, sosyal ve etkinlik kartları", color = ScanTokens.Muted, style = MaterialTheme.typography.bodySmall)
        }
        if (!isPro) ProBadge() else Text("Aç", color = ScanTokens.Blue, style = MaterialTheme.typography.labelLarge)
    }
}

@Composable
private fun LogoChoiceRow(selected: LogoMode, isPro: Boolean, onLocked: () -> Unit, onSelect: (LogoMode) -> Unit) {
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(7.dp)) {
        listOf(
            "ELXVRO" to LogoMode.ELXVRO,
            "Kendi logo" to LogoMode.CUSTOM,
            "Logosuz" to LogoMode.NONE
        ).forEach { (label, mode) ->
            val locked = !isPro && mode != LogoMode.ELXVRO
            CompactLightChip(
                text = "$label${if (locked) " PRO" else ""}",
                selected = selected == mode,
                modifier = Modifier.weight(1f)
            ) {
                if (locked) onLocked() else onSelect(mode)
            }
        }
    }
}

@Composable
private fun LockedProRow(text: String, onClick: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .background(ScanTokens.Warning.copy(alpha = 0.08f), RoundedCornerShape(10.dp))
            .border(1.dp, ScanTokens.Warning.copy(alpha = 0.20f), RoundedCornerShape(10.dp))
            .clickable(onClick = onClick)
            .padding(10.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Icon(Icons.Outlined.Image, contentDescription = null, tint = ScanTokens.Warning, modifier = Modifier.size(20.dp))
        Text(text, color = ScanTokens.Text, style = MaterialTheme.typography.bodySmall, modifier = Modifier.weight(1f).padding(start = 8.dp))
        ProBadge()
    }
}

@Composable
private fun Field(value: String, onValueChange: (String) -> Unit, label: String, password: Boolean = false) {
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        label = { Text(label) },
        singleLine = true,
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        visualTransformation = if (password) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,
        colors = OutlinedTextFieldDefaults.colors(
            focusedContainerColor = Color.White,
            unfocusedContainerColor = Color.White,
            focusedBorderColor = ScanTokens.Blue,
            unfocusedBorderColor = ScanTokens.Divider,
            focusedTextColor = ScanTokens.Text,
            unfocusedTextColor = ScanTokens.Text,
            focusedLabelColor = ScanTokens.Blue,
            unfocusedLabelColor = ScanTokens.Muted,
            cursorColor = ScanTokens.Blue
        )
    )
}

@Composable
private fun ColorSwatches(selected: Int, onSelect: (Int) -> Unit) {
    val colors = listOf(
        Color(0xFF0068F8), Color(0xFF1593FF), Color(0xFFCF24E8),
        Color(0xFF7539E8), Color(0xFF0D9F55), Color(0xFF101820)
    )
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp), verticalAlignment = Alignment.CenterVertically) {
        colors.forEach { color ->
            val value = color.toArgb()
            Box(
                modifier = Modifier
                    .size(30.dp)
                    .border(if (selected == value) 2.dp else 1.dp, if (selected == value) ScanTokens.Blue else ScanTokens.Divider, CircleShape)
                    .padding(4.dp)
                    .background(color, CircleShape)
                    .clickable { onSelect(value) }
            )
        }
    }
}

@Composable
private fun BackgroundSwatches(selected: Int, onSelect: (Int) -> Unit) {
    val colors = listOf(Color.White, Color(0xFFF7F8F9), Color(0xFFEAF2FF), Color(0xFFFFF4E5))
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        colors.forEach { color ->
            val value = color.toArgb()
            Box(
                modifier = Modifier
                    .size(32.dp)
                    .border(if (selected == value) 2.dp else 1.dp, if (selected == value) ScanTokens.Blue else ScanTokens.Divider, CircleShape)
                    .padding(4.dp)
                    .background(color, CircleShape)
                    .clickable { onSelect(value) }
            )
        }
    }
}

@Composable
private fun SecondaryAction(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    text: String,
    modifier: Modifier = Modifier,
    enabled: Boolean,
    onClick: () -> Unit
) {
    Column(
        modifier = modifier
            .height(64.dp)
            .background(Color.White, RoundedCornerShape(12.dp))
            .border(1.dp, ScanTokens.Divider, RoundedCornerShape(12.dp))
            .clickable(enabled = enabled, onClick = onClick),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(icon, contentDescription = null, tint = if (enabled) ScanTokens.Text else ScanTokens.Muted.copy(alpha = 0.5f), modifier = Modifier.size(20.dp))
        Text(text, color = if (enabled) ScanTokens.Text else ScanTokens.Muted.copy(alpha = 0.5f), style = MaterialTheme.typography.bodySmall, modifier = Modifier.padding(top = 3.dp))
    }
}

@Composable
private fun CompactLightChip(
    text: String,
    selected: Boolean,
    modifier: Modifier = Modifier,
    onClick: () -> Unit
) {
    Box(
        modifier = modifier
            .height(38.dp)
            .background(if (selected) ScanTokens.Blue.copy(alpha = 0.10f) else Color.White, RoundedCornerShape(10.dp))
            .border(1.dp, if (selected) ScanTokens.Blue else ScanTokens.Divider, RoundedCornerShape(10.dp))
            .clickable(onClick = onClick),
        contentAlignment = Alignment.Center
    ) {
        Text(text, color = if (selected) ScanTokens.Blue else ScanTokens.Text, style = MaterialTheme.typography.bodySmall, fontWeight = FontWeight.Medium)
    }
}

private fun logoLabel(mode: LogoMode): String = when (mode) {
    LogoMode.ELXVRO -> "ELXVRO logo"
    LogoMode.CUSTOM -> "Özel logo"
    LogoMode.NONE -> "Logosuz"
}

private fun primaryLabel(type: String): String = when (type) {
    "URL" -> "Web Sitesi URL"
    "Metin" -> "Metin"
    "Wi-Fi" -> "Wi-Fi adı (SSID)"
    "Kişi" -> "Ad Soyad"
    "Telefon" -> "Telefon numarası"
    "E-posta" -> "E-posta adresi"
    "SMS" -> "Telefon numarası"
    "Konum" -> "Enlem,Boylam"
    "Takvim" -> "Etkinlik başlığı"
    else -> "İçerik"
}

private fun secondaryLabel(type: String): String = when (type) {
    "Wi-Fi" -> "Wi-Fi şifresi"
    "Kişi" -> "Telefon"
    "SMS" -> "Mesaj"
    "Takvim" -> "Başlangıç (örn. 20261002T120000Z)"
    else -> "Ek bilgi"
}

private fun needsSecondary(type: String): Boolean = type in setOf("Wi-Fi", "Kişi", "SMS", "Takvim")
